import type { EncounterActionDefinition, EncounterInstance, EncounterOutcomeGroup } from './encounterTypes';

export const LEOPARD_ACTIONS: EncounterActionDefinition[] = [
  {
    id: 'observe',
    title: 'Observe',
    description: 'Read its posture, breathing and escape route before committing.',
    icon: 'observe',
    baseChance: 82,
    risk: 'low',
    timeMinutes: 1,
    noise: 'very_low',
    primarySkill: 'exploration',
    skillWeight: 1.3,
    effects: {
      strong_success: { knowledge: 18, alertness: -4, partyPanic: -3 },
      success: { knowledge: 12, partyPanic: -2 },
      partial_success: { knowledge: 7, alertness: 3 },
      failure: { alertness: 7, aggression: 4 },
      critical_failure: { aggression: 9, distance: -2, escalation: 10 },
    },
  },
  {
    id: 'stay_calm',
    title: 'Stay Calm',
    description: 'Keep your distance and avoid presenting yourself as a threat.',
    icon: 'calm',
    baseChance: 70,
    risk: 'low',
    timeMinutes: 1,
    noise: 'very_low',
    primarySkill: 'exploration',
    skillWeight: 1.2,
    effects: {
      strong_success: { aggression: -16, playerThreat: -14, partyPanic: -10, fear: -3 },
      success: { aggression: -10, playerThreat: -10, partyPanic: -6 },
      partial_success: { aggression: -4, playerThreat: -4, partyPanic: -2 },
      failure: { aggression: 6, playerThreat: 4, partyPanic: 5 },
      critical_failure: { aggression: 12, distance: -2, partyPanic: 12, escalation: 12 },
    },
  },
  {
    id: 'back_away',
    title: 'Back Away Slowly',
    description: 'Retreat without provoking it or turning your back.',
    icon: 'back_away',
    baseChance: 60,
    risk: 'low',
    timeMinutes: 2,
    noise: 'low',
    primarySkill: 'exploration',
    skillWeight: 1.25,
    effects: {
      strong_success: { distance: 8, aggression: -10, playerThreat: -5 },
      success: { distance: 5, aggression: -3 },
      partial_success: { distance: 2, aggression: 5 },
      failure: { distance: -3, aggression: 8, partyPanic: 5 },
      critical_failure: { distance: -5, aggression: 16, partyPanic: 14, escalation: 20 },
    },
  },
  {
    id: 'defend',
    title: 'Defend Yourself',
    description: 'Stand your ground and prepare to strike if it charges.',
    icon: 'defend',
    baseChance: 40,
    risk: 'high',
    timeMinutes: 1,
    noise: 'medium',
    primarySkill: 'hunting',
    skillWeight: 1.5,
    effects: {
      strong_success: { fear: 20, aggression: -4, playerThreat: 14, injury: 8 },
      success: { fear: 12, playerThreat: 12, injury: 5 },
      partial_success: { fear: 5, aggression: 5, playerThreat: 10, leadHealth: -5 },
      failure: { aggression: 15, distance: -4, leadHealth: -14, partyPanic: 15, escalation: 20 },
      critical_failure: { aggression: 22, distance: -6, leadHealth: -28, leadMorale: -10, partyPanic: 25, escalation: 28 },
    },
  },
  {
    id: 'distract_food',
    title: 'Distract with Food',
    description: 'Throw some meat aside and redirect its attention.',
    icon: 'food',
    baseChance: 55,
    risk: 'medium',
    timeMinutes: 1,
    noise: 'low',
    primarySkill: 'hunting',
    skillWeight: 1.0,
    requiresFood: true,
    effects: {
      strong_success: { distance: 7, aggression: -8, hunger: -8, playerThreat: -8 },
      success: { distance: 5, aggression: -4, hunger: -5 },
      partial_success: { distance: 2, aggression: 2 },
      failure: { aggression: 8, playerThreat: 4 },
      critical_failure: { aggression: 14, distance: -3, escalation: 15 },
    },
  },
  {
    id: 'leave_area',
    title: 'Leave the Area',
    description: 'The animal is no longer pressing the encounter. Withdraw safely.',
    icon: 'leave',
    baseChance: 100,
    risk: 'low',
    timeMinutes: 2,
    noise: 'very_low',
    onlyWhenSafe: true,
    effects: {
      strong_success: {}, success: {}, partial_success: {}, failure: {}, critical_failure: {},
    },
  },
];

export const LEOPARD_OUTCOMES: EncounterOutcomeGroup[] = [
  {
    id: 'safe',
    title: 'If Successful',
    tone: 'success',
    items: [
      { label: '+1 Raw Meat opportunity', icon: 'meat', revealAtKnowledge: 60 },
      { label: '+2 Fiber found on trail', icon: 'fiber', revealAtKnowledge: 45 },
      { label: 'Point of interest revealed', icon: 'knowledge', revealAtKnowledge: 25 },
      { label: '+10 Experience', icon: 'xp', revealAtKnowledge: 0 },
    ],
  },
  {
    id: 'flees',
    title: 'If It Flees',
    tone: 'neutral',
    items: [
      { label: 'Trail becomes accessible', icon: 'route', revealAtKnowledge: 15 },
      { label: 'New location may be unlocked', icon: 'location', revealAtKnowledge: 45 },
      { label: '+1 Knowledge', icon: 'knowledge', revealAtKnowledge: 0 },
    ],
  },
  {
    id: 'attacks',
    title: 'If It Attacks',
    tone: 'danger',
    items: [
      { label: 'Injury possible', icon: 'injury', revealAtKnowledge: 0 },
      { label: 'Lose food or supplies', icon: 'food', revealAtKnowledge: 20 },
      { label: 'Treat wounds required', icon: 'medical', revealAtKnowledge: 35 },
      { label: 'Survivor at risk', icon: 'risk', revealAtKnowledge: 0 },
    ],
  },
];

export function createLeopardEncounter(gameMinute: number, partyIds: string[]): EncounterInstance {
  const seed = Math.max(1, Math.floor(gameMinute * 9973 + partyIds.length * 7919));
  return {
    id: `enc_leopard_${gameMinute}_${partyIds.length}`,
    templateId: 'ENC_JUNGLE_LEOPARD',
    type: 'wildlife',
    stage: 'decision',
    title: 'JUNGLE ENCOUNTER',
    subtitle: 'A predator in the shadows',
    areaId: 'AREA_FOREST_EDGE',
    partyIds,
    seed,
    turn: 1,
    startedAtGameMinute: gameMinute,
    sceneImageUrl: '/poi-bg/center/Forest Edge.png',
    sceneAlt: 'Dense tropical jungle at the forest edge',
    intro: 'A leopard blocks your path near a jungle trail. It looks healthy and territorial. You have only a few seconds to decide.',
    narrative: [
      'A low growl rumbles through the trees.',
      'A leopard steps into view, its golden eyes fixed on you.',
      "It hasn't seen you as prey yet... but it's close.",
    ],
    actor: {
      id: 'leopard_actor',
      species: 'Leopard',
      displayName: 'Adult Leopard',
      description: 'Healthy adult; alert, territorial posture.',
      persistentEntityId: 'LEOPARD_FOREST_EDGE_01',
    },
    state: {
      distance: 12,
      alertness: 82,
      aggression: 48,
      fear: 17,
      hunger: 35,
      territoriality: 81,
      injury: 0,
      escapeRoute: 65,
      playerThreat: 42,
      noise: 25,
      partyPanic: 12,
      escalation: 44,
    },
    knowledge: {
      species: 45,
      behavior: 28,
      terrain: 35,
      total: 36,
    },
    outcomeGroups: LEOPARD_OUTCOMES,
    history: [
      { id: 'h1', turn: 0, timeLabel: '10:42', text: 'You enter a dense section of the jungle.', tone: 'info' },
      { id: 'h2', turn: 0, timeLabel: '10:43', text: 'Fresh paw prints are visible on the muddy trail.', tone: 'info' },
      { id: 'h3', turn: 0, timeLabel: '10:44', text: 'A leopard appears ahead, watching you from the rocks.', tone: 'warning' },
      { id: 'h4', turn: 1, timeLabel: '10:44', text: 'Waiting for your decision...', tone: 'info' },
    ],
    completed: false,
  };
}
